In [1]:
import pandas as pd

macbeth_df = pd.read_fwf('macbeth.txt')
macbeth_df.columns = ['text']

In [2]:
macbeth_df

                                                   text
0                                THE TRAGEDY OF MACBETH
1                                by William Shakespeare
2                                     Dramatis Personae
3                              DUNCAN, King of Scotland
4     MACBETH, Thane of Glamis and Cawdor, a general...
...                                                 ...
2660       We will perform in measure, time, and place.
2661          So thanks to all at once and to each one,
2662         Whom we invite to see us crown'd at Scone.
2663                                  Flourish. Exeunt.
2664                                          -THE END-

[2665 rows x 1 columns]

In [3]:
import numpy as np

splits = np.array_split(macbeth_df, 5)

# Split 0 -> Caesar Cipher

In [4]:
def caesar_encrypt(text, s=7):
    result = ""
    # transverse the plain text
    for i in range(len(text)):
        char = text[i]
        # Encrypt uppercase characters in plain text
        
        if (char.isupper()):
            result += chr((ord(char) + s-65) % 26 + 65)
        # Encrypt lowercase characters in plain text
        else:
            result += chr((ord(char) + s - 97) % 26 + 97)
    return result

In [5]:
caesar_df = splits[0]

caesar_df['key'] = 13

caesar_df['encrypt'] = [caesar_encrypt(text, shift) for text, shift in zip(caesar_df['text'].values, caesar_df['key'].values)]

In [6]:
caesar_df

,text,key,encrypt
0,THE TRAGEDY OF MACBETH,13,GURaGENTRQLaBSaZNPORGU
1,by William Shakespeare,13,olaJvyyvnzaFunxrfcrner
2,Dramatis Personae,13,QenzngvfaCrefbanr
3,"DUNCAN, King of Scotland",13,QHAPNAmaXvatabsaFpbgynaq
4,"MACBETH, Thane of Glamis and Cawdor, a general...",13,ZNPORGUmaGunarabsaTynzvfanaqaPnjqbemanatrareny...
...,...,...,...
528,"With his surcease, success; that but this blow",13,Jvguauvfafheprnfrmafhpprffbagungaohgaguvfaoybj
529,"Might be the be-all and the end-all -here,",13,Zvtugaoraguraornnyyanaqaguraraqnnyyanurerm
530,"But here, upon this bank and shoal of time,",13,Ohgaurermahcbaaguvfaonaxanaqafubnyabsagvzrm
531,We'ld jump the life to come. But in these cases,13,JrhyqawhzcagurayvsragbapbzroaOhgavaagurfrapnfrf
532,"We still have judgement here, that we but teach",13,Jrafgvyyaunirawhqtrzragaurermagungajraohgagrnpu